---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
# https://gethomepage.dev/widgets/services/

- Arr Services:
    - Jellyseerr:
        icon: jellyseerr.png
        href: http://192.168.0.45:5055
        description: Media Request Manager
        siteMonitor: http://jellyseerr:5055
        server: my-server
        container: jellyseerr
        show_version: true
        widget:
          type: jellyseerr
          url: http://jellyseerr:5055
          key: {{HOMEPAGE_VAR_JELLYSEERR_KEY}}
    - Radarr:
        icon: radarr.png
        href: http://192.168.0.45:7878        
        description: Movie Manager
        siteMonitor: http://radarr:7878
        server: my-server
        container: radarr
        widget:
          type: radarr
          url: http://radarr:7878  
          key: {{HOMEPAGE_VAR_RADARR_KEY}}
    - Sonarr:
        icon: sonarr.png
        href: http://192.168.0.45:8989
        description: TV Show Manager
        siteMonitor: http://sonarr:8989
        server: my-server
        container: sonarr
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: {{HOMEPAGE_VAR_SONARR_KEY}}
    - Profilarr:
        icon: profilarr.png
        href: http://192.168.0.45:6868
        description: Quality Profile Manager
        siteMonitor: http://profilarr:6868
        server: my-server
        container: profilarr
    - Huntarr:
        icon: huntarr.png
        href: http://192.168.0.45:9705
        description: Media Search Aggregator
        siteMonitor: http://huntarr:9705
        server: my-server
        container: huntarr
    - Bazarr:
        icon: bazarr.png
        href: http://192.168.0.45:6767
        description: Subtitle Manager
        siteMonitor: http://bazarr:6767
        server: my-server
        container: bazarr
        widget:
          type: bazarr
          url: http://bazarr:6767
          key: {{HOMEPAGE_VAR_BAZARR_KEY}}
    
- File Management:
    - Prowlarr:
        icon: prowlarr.png
        href: http://192.168.0.45:9696
        description: Usenet Indexer Manager
        siteMonitor: http://prowlarr:9696
        server: my-server
        container: prowlarr
        widget:
            type: prowlarr
            url: http://prowlarr:9696
            key: {{HOMEPAGE_VAR_PROWLARR_KEY}}

    - Immich:
        icon: immich.png
        href: http://192.168.0.45:2283/  # Replace with your ThinkCentre IP
        description: Photo and Video Management
        widget:
          type: immich
          url: http://immich_server:2283 # Use the container name if Homepage is in the same Docker network
          key: {{HOMEPAGE_VAR_IMMICH_KEY}}
          #fields: ["photos", "videos", "storage"] # Optional: choose what to display
          version: 2 # Optional: specify API version (default is 1)

    - NZBGet:
        icon: nzbget.png
        href: http://192.168.0.45:6789
        description: Usenet Downloader
        siteMonitor: http://nzbget:6789
        server: my-server
        container: nzbget
        widget:
            type: nzbget
            url: http://nzbget:6789
            username: {{HOMEPAGE_VAR_NZBGET_USER}}
            password: {{HOMEPAGE_VAR_NZBGET_PASS}}

    - Calibre-Web:
        icon: calibre-web.png
        href: https://192.168.0.45:8181
        description: eBook Management
        siteMonitor: http://calibre-web:8181
        server: my-server
        container: calibre

- Media Management:
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.0.45:8096
        description: Streaming Service
        siteMonitor: http://jellyfin:8096
        server: my-server
        container: jellyfin
        widget:
            type: jellyfin
            url: http://jellyfin:8096
            key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false
            enableMediaControl: false # optional, defaults to true
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: false # optional, defaults to true

# - System Monitoring:
#     - Glances Full Width:
#         widget:
#             type: glances
#             url: http://glances:61208/
#             metric: info 
#             version: 4 # http://192.168.0.45:61208/api/4/info

- System Monitoring:
    - CPU Usage:
        widget:
            type: glances
            url: http://192.168.0.45:61208/
            metric: cpu
            version: 4
    - Temperature:
        widget:
            type: glances
            url: http://192.168.0.45:61208/
            metric: "sensor:Package id 0"
            version: 4
    - Memory Usage:
        widget:
            type: glances
            url: http://192.168.0.45:61208/
            metric: memory
            version: 4
    - Disk Usage:
        widget:
            type: glances
            url: http://192.168.0.45:61208
            metric: fs:/host
            version: 4
    - Network Usage:
        widget:
            type: glances
            url: http://192.168.0.45:61208/
            metric: network:enp0s31f6 # Make sure this is the correct interface 'ip addr'
            version: 4
    - DiskStation Status:
        widget:
          type: diskstation
          url: http://192.168.0.11:5000/
          username: {{HOMEPAGE_VAR_NAS_USER}}
          password: {{HOMEPAGE_VAR_NAS_PASS}}
          volume: volume_1
          
- Speedtest:
    - Speedtest Tracker:
        #icon: speedtest-tracker.png
        href: http://192.168.0.45:8080
        widget:
            type: speedtest
            url: http://192.168.0.45:8080
            #version: 2
            key: APItoken
            bitratePrecision: 1 # Show 1 decimal point (e.g., 940.5 Mbps)

- Infrastructure:
    - Pi-hole:
        icon: pi-hole.png
        href: "http://192.168.0.45:8082/admin"
        widget:
          type: pihole
          url: "http://pihole" # Use container name if on same network
          version: 6           # CRITICAL for Pi-hole v6
          key: "{{HOMEPAGE_VAR_PIHOLE_PASS}}" # Use the variable from your .env

    - Reverse Proxy:
        icon: npm.png
        href: "http://192.168.0.45:81/"
        widget:
            type: npm
            url: http://192.168.0.45:81
            username: {{HOMEPAGE_VAR_NPM_USER}}
            password: {{HOMEPAGE_VAR_NPM_PASS}}

    - Portainer:
        icon: portainer.png
        href: https://192.168.0.45:9443
        description: Container Management
        siteMonitor: http://portainer:9000
        server: my-server
        container: portainer

- Smart Home Sensors:
    - Power Usage:
        icon: domoticz.png
        href: http://192.168.0.45:8081/#/Devices/1/Log
        widget:
          type: customapi
          url: "http://192.168.0.45:8081/json.htm?type=command&param=getdevices&rid=1"
          method: GET
          mappings:
            - field: result[0].Usage
              label: Current
              format: text
            - field: result[0].CounterToday
              label: Usage 24h
              format: text
            - field: result[0].CounterDelivToday
              label: Return 24h
              format: text
            - field: result[0].LastUpdate
              label: Last Seen
              format: datetime
              dateformat: "DD-MM-YYYY HH:mm:ss"

    - Gas Usage:
        icon: domoticz.png
        href: http://192.168.0.45:8081/#/Devices/2/Log
        widget:
          type: customapi
          url: "http://192.168.0.45:8081/json.htm?type=command&param=getdevices&rid=2"
          method: GET
          mappings:
            - field: result[0].CounterToday
              label: Usage 24h
              format: text
            - field: result[0].LastUpdate
              label: Last Seen
              format: datetime
              dateformat: "DD-MM-YYYY HH:mm:ss"