---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

#base: /homepage

layout:

  Media Management:
    style: row
    columns: 1

  Arr Services:
    header: false
    style: row
    columns: 4

  File Management:
    header: false
    style: row
    columns: 3

  System Monitoring:
    style: row
    columns: 2  # 3x2 grid for the other Glances widgets
   
  Speedtest:
    header: false
    style: row
    columns: 1 

  Infrastructure:
    style: row
    columns: 2

  Smart Home Sensors:
    style: row
    columns: 2

background:
  image: https://images7.alphacoders.com/601/601841.jpg?auto=format # Terminator
  #image: https://wallpapercave.com/wp/wp6889832.jpg?auto=format # Dune
  #image: https://static.vecteezy.com/system/resources/thumbnails/013/447/673/original/the-matrix-raining-binary-code-background-free-video.jpg?auto=format # Matrix
  blur: lg # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  #saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  #brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 25 # 0-100